### ISSUE TITLE
AddPipelines::execute() method uses wrong API Path

### ISSUE THREAD

**Issue by kaktusas2598** [jmleroux/circleci-php-client#49]
First of all, thank you so much for creating this package!

I believe some endpoints (for v2 API) are wrong though:

In AllPipelines.php, execute() method:

        $uri = sprintf('project/%s/pipeline', $projectSlug);

Should be I think:

        $uri = sprintf('/pipeline?org-slug=%s', $projectSlug);

**Comment by kaktusas2598** [comment]
https://circleci.com/docs/api/v2/index.html#operation/listPipelines

**Comment by jmleroux** [comment]
Thank you for raising this issue, I will have a look at it.
By the way, this is the kind of stuff hard to test because we lack of some validation tool from CircleCI, like a swagger file to validate existing endpoints. :cry:

**Comment by jmleroux** [comment]
After having a look at the API, there is no issue with the endpoint URL.

But it does not mean there is no issue, as I think this class is very badly named.

The description of the endpoint is correst: https://github.com/jmleroux/circleci-php-client/blob/master/src/Api/Pipeline/AllPipelines.php#L12
> Retrieve pipelines **of a project**, optionally filtered by branch.

But in this case I should have named it like `Jmleroux\CircleCi\Api\Project\AllPipelines` because it scoped to the project.

And add another endpoint for your need wich is not scoped by project, like the doc says:
> Returns all pipelines **for the most recently built projects** (max 250) you follow in an organization.


Now my issue is how to refactor/rename the existing class without BC break. :thinking:

**Comment by jmleroux** [comment]
I made a draft PR without BC break. What do you think about it?

**Comment by kaktusas2598** [comment]
@jmleroux Yeah, that's cool, but I kind of needed ability to get all pipelines, so is there any other way to get that?

**Comment by kaktusas2598** [comment]
Not sure what you mean by "BC break", surely you could add another class to get all pipelines? I can try doing that tomorrow at work and submitting PR if you're too busy

**Comment by jmleroux** [comment]
BC break = backward compatibility break. Or how to move a class without breaking contract with libraries using this client :wink:

**Comment by kaktusas2598** [comment]
Ah, I understand, but that's a shame, basically I was trying to get average time it takes a build to fail and I'm not sure I can do that without getting all the pipelines first

**Comment by jmleroux** [comment]
I added a commit in the PR that could suit your need :wink:

**Comment by jmleroux** [comment]
Available in v5.1.2

**Comment by kaktusas2598** [comment]
Merci beaucoup Jean! I can see, looks like ListPipelines is exactly what I need, thanks again!
